###
POST http://localhost:8080/locations/
Content-type: application/json

{
    "lat": 70,
    "lon": 80
}

###
GET http://localhost:8080/locations/

###
GET http://localhost:8080/locations/1

###
DELETE http://localhost:8080/locations/1
